### ISSUE TITLE
Fix cStable Balances SQL Query Issue

### ISSUE THREAD

**Issue by chapati23** [mento-protocol/airdrop-snapshot#10]
We found a small but consequential SQL bug in the query. See https://github.com/mento-protocol/airdrop-snapshot/pull/9#pullrequestreview-2008627286 for details

The same bug is also present in the cStable Balances Query, therefore we need to re-run it, meaning:

- Fix Dune Query
- Export 16 fresh monthly snapshots
- Re-run the scripts to fetch validator & validator group balances from archive nodes
- Spot-check output

**Comment by RyRy79261** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/wdF5Cdz9K0/estimate/6) in Sprint Poker #​​19

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
